monolog:
    handlers:
        searchEngine:
            level: debug
            type: rotating_file
            max_files: 14
            path: '%kernel.logs_dir%/%kernel.environment%/main.log'
        main:
            level: debug
            type: rotating_file
            max_files: 14
            path: '%kernel.logs_dir%/%kernel.environment%/main.log'
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
